CocoFarm/CocoFarm/Models/Produs.cs
using CocoFarm.DataAccess;

namespace CocoFarm.Models
{
    public class Produs : IEntityWithId
    {
        public int Id { get; set; }
        public string Denumire { get; set; }
        public string Cod { get; set; }
        public string Descriere { get; set; }
    }
}

CocoFarm/CocoFarm/Controllers/CatalogProduseController.cs
using System;
using System.Data.Entity;
using System.Linq;

using CocoFarm.DataAccess;
using CocoFarm.Model;
using System.Collections.Generic;
using System.Web.Mvc;

namespace CocoFarm.Controllers
{
    public class CatalogProduseController : Controller
    {
        private readonly IDataStore<Product, Guid> store;
        private readonly IDataStore<ProductCategory, Guid> categoryStore;

        public CatalogProduseController(
            IDataStore<Product, Guid> store,
            IDataStore<ProductCategory, Guid> categoryStore)
        {
            this.store = store;
            this.categoryStore = categoryStore;
        }

        public ActionResult Index()
        {
            var produse = ((DbSet<Product>)store.GetAll()).Include(p => p.Category);
            return View(produse.ToList());
        }

        public ActionResult Details(Guid id)
        {
            var produs = store.GetById(id);
            return View(produs);
        }

        public ActionResult Create()
        {
            ViewBag.Categories = categoryStore.GetAll().ToList();

            return View();
        }

        [HttpPost]
        public ActionResult Create(Product produs, Guid categoryId)
        {


            if (ModelState.IsValid)
            {
                produs.Category = categoryStore.GetById(categoryId);

                store.Create(produs);
                return RedirectToAction("Index");
            }

            ViewBag.Categories = categoryStore.GetAll().ToList();
            return View(produs);
        }

        public ActionResult Edit(Guid id)
        {
            var produs = store.GetById(id);
            return View(produs);
        }

        [HttpPost]
        public ActionResult Edit(Product produs)
        {
            store.Update(produs);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(Guid id)
        {
            var produs = store.GetById(id);
            return View(produs);
        }

        [HttpPost]
        public ActionResult Delete(Product produs)
        {

            store.Delete(produs.Id);
            return RedirectToAction("Index");
        }
    }
}

CocoFarm/CocoFarm/Controllers/HomeController.cs
using System.Web.Mvc;

namespace CocoFarm.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

    }
}

CocoFarm/CocoFarm/Views/CatalogProduse/Create.cshtml
@{
    ViewBag.Title = "Create";
}
@using CocoFarm.Model
@model CocoFarm.Model.Product
<h2>Adaugare produs</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <fieldset>
        <legend>Produs nou</legend>
        <div>
            @Html.ValidationSummary()
        </div>
        <div>
            @Html.LabelFor(model => model.Denumire)
            @Html.EditorFor(model => model.Denumire)
        </div>
        <div>
            @Html.LabelFor(model => model.Cod)
            @Html.EditorFor(model => model.Cod)
            @Html.ValidationMessageFor(model => model.Cod)
        </div>
        <div>
            @Html.LabelFor(model => model.Descriere)
            @Html.EditorFor(model => model.Descriere)
        </div>
        <div>
            @Html.LabelFor(model => model.Price)
            @Html.EditorFor(model => model.Price)
        </div>
        <div>
            @Html.LabelFor(model => model.Category)
            @{
                var categories = from cat in (IEnumerable<ProductCategory>)ViewBag.Categories
                                 select new SelectListItem {Text = cat.Name, Value = cat.Id.ToString()};
            }
            @Html.DropDownList("CategoryId", categories)
        </div>
    </fieldset>
    <p>
        <input type="submit" value="Adaugă" /> |
        @Html.ActionLink("Înapoi în listă", "Index")
    </p>
}

CocoFarm/CocoFarm/Views/CatalogProduse/Delete.cshtml
@{
    ViewBag.Title = "Delete";
}
@model CocoFarm.Model.Product
<h2>Ștergere produs</h2>

<fieldset>
    <legend>Produsul ce urmeaza a fi șters</legend>
    <div>
        @Html.LabelFor(model => model.Denumire)
        @Html.DisplayFor(model => model.Denumire)
    </div>
    <div>
        @Html.LabelFor(model => model.Cod)
        @Html.DisplayFor(model => model.Cod)
    </div>
    <div>
        @Html.LabelFor(model => model.Descriere)
        @Html.DisplayFor(model => model.Descriere)
    </div>
    <div>
        @Html.LabelFor(model => model.Price)
        @Html.DisplayFor(model => model.Price)
    </div>
</fieldset>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Șterge" /> |
        @Html.ActionLink("Înapoi în listă", "Index")
    </p>
}

CocoFarm/CocoFarm/Views/CatalogProduse/Details.cshtml
@{
    ViewBag.Title = "Details";
}
@model CocoFarm.Model.Product
<h2>Detalii produs</h2>

<fieldset>
    <legend>@Html.DisplayNameFor(model => model.Denumire)</legend>
    <div>
        @Html.LabelFor(model => model.Denumire)
        @Html.DisplayFor(model => model.Denumire)
    </div>
    <div>
        @Html.LabelFor(model => model.Cod)
        @Html.DisplayFor(model => model.Cod)
    </div>
    <div>
        @Html.LabelFor(model => model.Descriere)
        @Html.DisplayFor(model => model.Descriere)
    </div>
    <div>
        @Html.LabelFor(model => model.Price)
        @Html.DisplayFor(model => model.Price)
    </div>
</fieldset>

<p>
    @Html.ActionLink("Modifică", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Înapoi în listă", "Index")
</p>

CocoFarm/CocoFarm/Views/CatalogProduse/Edit.cshtml
@{
    ViewBag.Title = "Edit";
}
@model CocoFarm.Model.Product

<h2>Editare produs</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <fieldset>        
        <legend>@Html.DisplayNameFor(model => model.Denumire)</legend>
        <div>
            @Html.LabelFor(model => model.Denumire)
            @Html.EditorFor(model => model.Denumire)
        </div>
        <div>
            @Html.LabelFor(model => model.Cod)
            @Html.EditorFor(model => model.Cod)
        </div>
        <div>
            @Html.LabelFor(model => model.Descriere)
            @Html.EditorFor(model => model.Descriere)
        </div>
        <div>
            @Html.LabelFor(model => model.Price)
            @Html.EditorFor(model => model.Price)
        </div>
        <p>
            <input type="submit" value="Salvează" />
        </p>
    </fieldset>
}

CocoFarm/CocoFarm/Views/CatalogProduse/Index.cshtml
@{
    ViewBag.Title = "Catalog produse";
}
@model IEnumerable<CocoFarm.Model.Product>

<h2>Catalog produse</h2>
<p>
    @Html.ActionLink("Adaugă produs", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Denumire)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cod)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descriere)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category.Name)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Denumire)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cod)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descriere)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category.Name)
            </td>
            <td>
                @Html.ActionLink("Modifică", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Detalii", "Details", new { id = item.Id }) |
                @Html.ActionLink("Șterge", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

CocoFarm/CocoFarm/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Acasa";
}

<h2>Prima pagină</h2>

@Html.ActionLink("Catalog produse", "Index", "CatalogProduse")

CocoFarm/CocoFarm/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <meta name="description" content="This is a wonderful site" />
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>